services:
  - type: web
    name: milkmind-mini-demo
    runtime: static
    autoDeploy: true
    branch: main
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
